### PR TITLE
fix CI check logic.  And format code.

### LINKED ISSUE #11: Fix CI check for code formatting
As [noted here](https://github.com/python-trio/exceptiongroup/pull/10#issuecomment-457059725), we have code in `ci/travis.sh` to check for having run black, but it's broken.

I think we want a PR that:

1. makes it `if ! black ...`, to fix the check.
2. runs black over the code with the given configuration, so that the fixed check will pass
3. does nothing else, because it's hard to review code changes mixed in with formatting changes

### PR DESCRIPTION
**Pull request by WindSoilder**
fixes: #11

### CODE REVIEW

**Comment by WindSoilder** [comment]
It's worth to note that for now we use `--line-length` with value `79` (not default `88`) to format code.
Is it ok ?  Or we should use default value `88` ?

**Comment by njsmith** [comment]
79 is what we use in all the other trio projects... maybe at some point I need to adjust to our long-line future, but for now all my terminals and editor windows are 80 characters to match the traditional default, so I prefer to stick to 79 for the code :-).

Recently black gained the ability to specify this line length in a config file: https://black.readthedocs.io/en/stable/pyproject_toml.html

Maybe we should add

```toml
[tool.black]
line-length = 79
```

To our `pyproject.toml`, and then we don't need to pass `-l 79` on the command line?

**Comment by WindSoilder** [comment]
I like that idea, because user don't need to worry about the `line-length` arguments when formating code.

**Comment by njsmith** [comment]
Thanks!

**Pull request merged**
